### ISSUE TITLE
Deployment fails when current desired capacity is not within [min size, max size]

### ISSUE THREAD

**Issue by asmgf** [traveloka/ansible-asg-rolling-deployment#20]
When I deploy into a newly created ASG (created with min and max size of 0), the playbook fails with
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (ValidationError) when calling the UpdateAutoScalingGroup operation: Desired capacity:0 must be between the specified min size:1 and max size:2
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update autoscaling group: An error occurred (ValidationError) when calling the UpdateAutoScalingGroup operation: Desired capacity:0 must be between the specified min size:1 and max size:2"}
```

Should we update `ec2_asg.desired_capacity` to clamp current desired capacity between min and max size if it's not specified explicitly?

**Comment by salvianreynaldi** [comment]
how did you execute the playbook, @asmgf ?
From https://github.com/traveloka/ansible-asg-rolling-deployment/blob/03e030b1f3246d41f1f69ed7569424e9ff4757e4/tasks/main.yml#L93-L95
I think that if no size parameter is specified, by default it will retrieve the ASG's current min, desired, and max capacity, which should be 0-0-0 in your case, not 1-0-2

**Comment by asmgf** [comment]
I do specify `asg_min_size` and `asg_max_size`. Am I supposed to specify `asg_desired_capacity` as well? I don't set it currently as there is a scaling policy.
