### ISSUE TITLE
Playbook doesn't update ASG tag

### ISSUE THREAD

**Issue by salvianreynaldi** [traveloka/ansible-asg-rolling-deployment#6]
It makes some of the instance tags (AMI id, service version) misleading, because it doesn't reflect the reality

**Comment by salvianreynaldi** [comment]
One challenge is the fact that
https://docs.ansible.com/ansible/latest/modules/ec2_asg_facts_module.html and https://docs.ansible.com/ansible/2.3/ec2_asg_module.html doesn't return & expect the same format of `tags`

**Comment by arpit9508** [comment]
PR for the fix : https://github.com/traveloka/ansible-asg-rolling-deployment/pull/19

**Comment by salvianreynaldi** [comment]
solved by #19
